# This file is used by GitHub Classroom to drive the tests for the assignment.
# Do not edit this file.

source("function.R")
x = readLines(file("stdin"), warn=FALSE)

eval(parse(text=x))

# mySumFunction(11,8)
